name: Build and Deploy
on:
  push:
    branches:
      - main  # Insert your main branch name here (default: main)
  workflow_dispatch:
jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    steps:
    - name: Check files
      shell: bash
      run: ls -al
    - uses: victorbnl/build-signed-apk@main
      with:
        keystore_b64: ${{ secrets.KEYSTORE }}
        keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
        key_alias: ${{ secrets.KEY_ALIAS }}
        key_password: ${{ secrets.KEY_PASSWORD }}