name: Build and Release Signed APK

permissions:
  contents: write
on:
  push:
    tags: 
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $GITHUB_REF
      - uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.KEYSTORE }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_alias: ${{ secrets.KEY_ALIAS }}
          key_password: ${{ secrets.KEY_PASSWORD }}
          java_version: '17'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: app/build/outputs/apk/release/app-release.apk
  deploy:
    name: Deploy APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - uses: softprops/action-gh-release@v1
        with:
          files: app-release.apk